# Ansbile inventory file

[defaults]
inventory = /mydb
private_key_file= /root/Appu9455.pem
host_key_checking= false
remote_user= ec2-user

[privilege_escalation]

become = true
become_method = sudo
become_user = root
become_ask_pass = false

==========================================================================
#Ansible playbook
- hosts: ["tag_Name_node_1", "tag_Name_node_2", "tag_Name_node_3", ]  
  tasks:
  - name: "installing python3"
    shell: "yum install python3 -y"
  - name: "Repository"
    yum_repository:
       name: "Docker"
       description: "Docker Repo"
       baseurl: "https://download.docker.com/linux/centos/7/x86_64/stable"
       gpgcheck: "no"
  -  name: "creating docker package"
     package:
        name: "docker-ce-18.09.1-3.el7.x86_64"
        state: present

  -  name: "service starting"
     service:
       name: "docker"
       state: started
       enabled: yes

  -  name: "Installing python"
     command: "pip3 install docker"


  - name: "creating folder and copy in that folder"
    file:
      path: "/myfile"
      state: directory
  - name: "Copying local files"
    copy:
      src: "hello.html"
      dest: "/myfile/"

  - name: "Creating OS"
    docker_container:
      name: "Myweb4396"
      image: "httpd"
      state: started
      exposed_ports:
      - "80"
      ports:
      - "4499:80"
      volumes:
      - /myfile:/usr/local/apache2/htdocs/

